<a href="https://colab.research.google.com/github/Mirza-MohammedJunaid-au28/Machine-Learning-Tutorial/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

Python List to Numpy Array

In [4]:
listt = [1,2,3,4,5]
print(listt,'type : ',type(listt))
n_arr = np.array(listt) # we can pass datatype of element also using np.array(list,dtype=int)
print(n_arr,'type : ',type(n_arr))

[1, 2, 3, 4, 5] type :  <class 'list'>
[1 2 3 4 5] type :  <class 'numpy.ndarray'>


Dimensions in Numpy Array

In [26]:
# 1d Array
a = np.array([1,2,3,4,5])
print(a)
print('Shape : ',a.shape) #shows no of rows and columns note : but it is 1d therefore it only shows no of column
print('Dimensions : ',a.ndim) # shown dimension of numpy array
print('Size : ',a.size) # no of element in numpy array
print('Datatype : ',a.dtype) # datatype of element in numpy array

[1 2 3 4 5]
Shape :  (5,)
Dimensions :  1
Size :  5
Datatype :  int64


In [8]:
# 2d Array
b = np.array([(1,2,3,4,5),(6,7,8,9,10)])
print(b)
b.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


(2, 5)

Initial Placeholder in Numpy  Arrays

In [10]:
# create a numpy array of zeros
x = np.zeros((4,5),dtype=int) # np.zeros((no of rows,no of columns))
x

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [12]:
# create a numpy array of ones
y = np.ones((4,5),dtype=int)
y

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
# create a numpy array of a particular value for eg : 10
z = np.full((4,5),10,dtype=int)
z

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [15]:
# create a numpy array with random values
r = np.random.random((3,3)) # value will range between 0 and 1
r

array([[0.50150754, 0.876078  , 0.43497215],
       [0.13579937, 0.76197358, 0.86500969],
       [0.44959814, 0.92932403, 0.83021822]])

In [17]:
# create a numpy array with random values in a specific range
rr = np.random.randint(1,100,(3,3)) #randint(starting range,ending range,(rows,column))
rr

array([[60, 44, 55],
       [78, 76, 15],
       [91, 88, 92]])

In [19]:
# create a numpy array of evenly spaced values in specific range
rrr = np.linspace(10,30,5) # linspace(start,end,no of value from this range with evenly spaced)
rrr

array([10., 15., 20., 25., 30.])

In [22]:
# create a numpy array of with step values in specific range
rrrr = np.arange(10,30,2) # linspace(start,end,step)
rrrr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [14]:
# create an Identity Matrix
i = np.eye(4)  # np.eye(no of column and no of row) there will be only one single value cuz the matrix should have equal no of columns and row like (3,3),(4,4) for 4,4 we will pass 4
i

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])